export const PERMISSIONS = [
  {
    id: 1,
    name: 'PURCHASE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 1,
    },
  },
  {
    id: 2,
    name: 'PURCHASE_PRICE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 2,
    },
  },
  {
    id: 3,
    name: 'PURCHASE_DISCOUNT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 3,
    },
  },
  {
    id: 4,
    name: 'PURCHASE_DELIVERY',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 4,
    },
  },
  {
    id: 5,
    name: 'SELL',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 5,
    },
  },
  {
    id: 6,
    name: 'SELL_QUICK',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 6,
    },
  },
  {
    id: 7,
    name: 'SELL_PRICE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 7,
    },
  },
  {
    id: 8,
    name: 'SELL_DISCOUNT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 8,
    },
  },
  {
    id: 9,
    name: 'SELL_DELIVERY',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 9,
    },
  },
  {
    id: 10,
    name: 'PURCHASE_BOOK',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 10,
    },
  },
  {
    id: 11,
    name: 'PURCHASE_BOOK_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 11,
    },
  },
  {
    id: 12,
    name: 'PURCHASE_BOOK_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 12,
    },
  },
  {
    id: 13,
    name: 'SELL_BOOK',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 13,
    },
  },
  {
    id: 14,
    name: 'SELL_BOOK_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 14,
    },
  },
  {
    id: 15,
    name: 'SELL_BOOK_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 15,
    },
  },
  {
    id: 16,
    name: 'DUE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 16,
    },
  },
  {
    id: 17,
    name: 'DUE_HISTORY',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 17,
    },
  },
  {
    id: 18,
    name: 'DUE_DETAILS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 18,
    },
  },
  {
    id: 19,
    name: 'DUE_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 19,
    },
  },
  {
    id: 20,
    name: 'DUE_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 20,
    },
  },
  {
    id: 21,
    name: 'DUE_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 21,
    },
  },
  {
    id: 22,
    name: 'EXPENSE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 22,
    },
  },
  {
    id: 23,
    name: 'EXPENSE_LIST',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 23,
    },
  },
  {
    id: 24,
    name: 'EXPENSE_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 24,
    },
  },
  {
    id: 25,
    name: 'EXPENSE_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 25,
    },
  },
  {
    id: 26,
    name: 'EXPENSE_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 26,
    },
  },
  {
    id: 27,
    name: 'EXPENSE_CATEGORY_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 27,
    },
  },
  {
    id: 28,
    name: 'EXPENSE_CATEGORY_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 28,
    },
  },
  {
    id: 29,
    name: 'EXPENSE_CATEGORY_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 29,
    },
  },
  {
    id: 30,
    name: 'MARKETING_SHOP',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 30,
    },
  },
  {
    id: 31,
    name: 'CONTACT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 31,
    },
  },
  {
    id: 32,
    name: 'CONTACT_CUSTOMER',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 32,
    },
  },
  {
    id: 33,
    name: 'CONTACT_SUPPLIER',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 33,
    },
  },
  {
    id: 34,
    name: 'CONTACT_CUSTOMER_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 34,
    },
  },
  {
    id: 35,
    name: 'CONTACT_SUPPLIER_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 35,
    },
  },
  {
    id: 36,
    name: 'CONTACT_CUSTOMER_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 36,
    },
  },
  {
    id: 37,
    name: 'CONTACT_CUSTOMER_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 37,
    },
  },
  {
    id: 38,
    name: 'CONTACT_SUPPLIER_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 38,
    },
  },
  {
    id: 39,
    name: 'CONTACT_SUPPLIER_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 39,
    },
  },
  {
    id: 40,
    name: 'PRODUCT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 40,
    },
  },
  {
    id: 41,
    name: 'PRODUCT_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 41,
    },
  },
  {
    id: 42,
    name: 'PRODUCT_DETAILS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 42,
    },
  },
  {
    id: 43,
    name: 'STOCK_HISTORY',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 43,
    },
  },
  {
    id: 44,
    name: 'STOCK_UPDATE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 44,
    },
  },
  {
    id: 45,
    name: 'PRODUCT_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 45,
    },
  },
  {
    id: 46,
    name: 'PRODUCT_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 46,
    },
  },
  {
    id: 47,
    name: 'STOCK',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 47,
    },
  },
  {
    id: 48,
    name: 'SMS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 48,
    },
  },
  {
    id: 49,
    name: 'SMS_HISTORY',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 49,
    },
  },
  {
    id: 50,
    name: 'SMS_PURCHASE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 50,
    },
  },
  {
    id: 51,
    name: 'BUSINESS_OVERVIEW',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 51,
    },
  },
  {
    id: 52,
    name: 'TOPUP',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 52,
    },
  },
  {
    id: 53,
    name: 'ONLINE_STORE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 53,
    },
  },
  {
    id: 54,
    name: 'ONLINE_STORE_MESSAGE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 54,
    },
  },
  {
    id: 55,
    name: 'ONLINE_STORE_SETTINGS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 55,
    },
  },
  {
    id: 56,
    name: 'ONLINE_STORE_PRODUCT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 56,
    },
  },
  {
    id: 57,
    name: 'ONLINE_STORE_ORDERS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 57,
    },
  },
  {
    id: 58,
    name: 'ONLINE_STORE_ORDER_DETAILS',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 58,
    },
  },
  {
    id: 59,
    name: 'ONLINE_STORE_THEME',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 59,
    },
  },
  {
    id: 60,
    name: 'ONLINE_STORE_SHIPPING',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 60,
    },
  },
  {
    id: 61,
    name: 'SHOP_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 61,
    },
  },
  {
    id: 62,
    name: 'SETTINGS_QR',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 62,
    },
  },
  {
    id: 63,
    name: 'SETTINGS_RECYCLEBIN',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 63,
    },
  },
  {
    id: 64,
    name: 'ACCESS_MANAGEMENT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 64,
    },
  },
  {
    id: 65,
    name: 'ACCESS_MANAGEMENT_ROLE_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 65,
    },
  },
  {
    id: 66,
    name: 'ACCESS_MANAGEMENT_ROLE_ASSIGN',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 66,
    },
  },
  {
    id: 67,
    name: 'CONTACT_EMPLOYEE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 67,
    },
  },
  {
    id: 68,
    name: 'CONTACT_EMPLOYEE_ADD',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 68,
    },
  },
  {
    id: 69,
    name: 'CONTACT_EMPLOYEE_EDIT',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 69,
    },
  },
  {
    id: 70,
    name: 'CONTACT_EMPLOYEE_DELETE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 70,
    },
  },
  {
    id: 71,
    name: 'DIGITAL_BALANCE',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 71,
    },
  },
  {
    id: 72,
    name: 'SHOP_RESET',
    guard_name: 'api',
    created_at: null,
    updated_at: null,
    pivot: {
      shop_role_id: 3,
      shop_permission_id: 72,
    },
  },
];
