import type { Metadata } from "next";
import { ThemeProvider } from "@/themes";
import { Inter } from "next/font/google";
import Dashboard from "@/components/layouts/Dashboard";

import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" >
            <body className={inter.className} suppressHydrationWarning>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Dashboard>
                        {children}
                    </Dashboard>
                </ThemeProvider>
            </body>
        </html>
    );
}