import { IAsideBarMenuItem } from '@/types/SidebarLinks';

const SidebarLinks: IAsideBarMenuItem[] = [
  {
    id: 1,
    title: 'Home',
    bn_title: 'হোম',
    image: '/images/features/home.svg',
    link: '/home',
    permissionId: 'BUSINESS_OVERVIEW',
  },
  {
    id: 200,
    title: 'Purchase',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase.svg',
    link: '/purchase',
    permissionId: 'PURCHASE',
  },
  {
    id: 202,
    title: 'Sell',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/sell.svg',
    link: '/sell',
    permissionId: 'SELL',
  },
  {
    id: 201,
    title: 'Purchase list',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase_list.svg',
    link: '/purchase-list',
    permissionId: 'PURCHASE_BOOK',
  },
  {
    id: 203,
    title: 'Transaction',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/transaction.svg',
    link: '/sell-list',
    permissionId: 'SELL_BOOK',
  },
  {
    id: 204,
    title: 'Due List',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/due.svg',
    link: '/due',
    permissionId: 'DUE',
  },
  {
    id: 205,
    title: 'Expense',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/expense.svg',
    link: '/expense',
    permissionId: 'EXPENSE',
  },
  {
    id: 206,
    title: 'Contact',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/contact.svg',
    link: '/contact',
    permissionId: 'CONTACT',
  },

  {
    id: 301,
    title: 'Product List',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/product_list.svg',
    link: '/product',
    permissionId: 'PRODUCT',
  },
  {
    id: 302,
    title: 'Stock Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/stock_management.svg',
    link: '/stock',
    permissionId: 'STOCK',
  },
  {
    id: 303,
    title: 'Access Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/access_management.svg',
    link: '/access-management',
    permissionId: 'ACCESS_MANAGEMENT',
  },
  {
    id: 304,
    title: 'Printer',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/printer.svg',
    link: '/printer',
    permissionId: 'ACCESS_MANAGEMENT',
  },

  {
    id: 401,
    title: 'Online Shop',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/online_shop.svg',
    link: '/online-shop',
    permissionId: 'ONLINE_STORE',
  },
  {
    id: 402,
    title: 'Sms Marketing',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/sms_marketing.svg',
    link: '/sms',
    permissionId: 'SMS',
  },
];

export const SidebarLinksFree = [
  {
    id: 1,
    title: 'Home',
    bn_title: 'হোম',
    image: '/images/features/home.svg',
    link: '/home',
  },
  {
    id: 200,
    title: 'Purchase',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase.svg',
    link: '/purchase',
  },
  {
    id: 202,
    title: 'Sell',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/sell.svg',
    link: '/sell',
  },
  {
    id: 201,
    title: 'Purchase list',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase_list.svg',
    link: '/purchase-list',
  },
  {
    id: 203,
    title: 'Transaction',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/transaction.svg',
    link: '/sell-list',
  },
  {
    id: 204,
    title: 'Due List',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/due.svg',
    link: '/due',
  },
  {
    id: 205,
    title: 'Expense',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/expense.svg',
    link: '/expense',
  },
  {
    id: 206,
    title: 'Contact',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/contact.svg',
    link: '/contact',
  },

  {
    id: 301,
    title: 'Product List',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/product_list.svg',
    link: '/product',
  },
  {
    id: 302,
    title: 'Stock Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/stock_management.svg',
    link: '/stock',
  },
  {
    id: 303,
    title: 'Access Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/access_management.svg',
    link: '/access-management',
  },
  {
    id: 304,
    title: 'Printer',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/printer.svg',
    link: '/printer',
  },
  {
    id: 4,
    title: 'Advanced',
    bn_title: 'স্টক খাতা',
    image: '/images/features/advanced.svg',
    link: '#',
  },
];

export const SidebarLinksStandard = [
  {
    id: 1,
    title: 'Home',
    bn_title: 'হোম',
    image: '/images/features/home.svg',
    link: '/home',
  },

  {
    id: 200,
    title: 'Purchase',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase.svg',
    link: '/purchase',
  },
  {
    id: 201,
    title: 'Purchase list',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/purchase_list.svg',
    link: '/purchase-list',
  },
  {
    id: 202,
    title: 'Sell',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/sell.svg',
    link: '/sell',
  },
  {
    id: 203,
    title: 'Transaction',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/transaction.svg',
    link: '/sell-list',
  },
  {
    id: 204,
    title: 'Due List',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/due.svg',
    link: '/due',
  },
  {
    id: 205,
    title: 'Expense',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/expense.svg',
    link: '/expense',
  },
  {
    id: 206,
    title: 'Contact',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/contact.svg',
    link: '/contact',
  },
  // {
  //   id: 3,
  //   title: 'Standard',
  //   bn_title: 'স্টক খাতা',
  //   image: '/images/features/standard.svg',
  //   link: '#',
  //   children: [],
  // },
  {
    id: 301,
    title: 'Product List',
    bn_title: 'স্টক ড্যাশবোর্ড',
    image: '/images/features/product_list.svg',
    link: '/product',
  },
  {
    id: 302,
    title: 'Stock Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/stock_management.svg',
    link: '/stock',
  },
  {
    id: 303,
    title: 'Access Management',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/access_management.svg',
    link: '/access-management',
  },
  {
    id: 304,
    title: 'Printer',
    bn_title: 'স্টক ইতিহাস',
    image: '/images/features/printer.svg',
    link: '/printer',
  },
  {
    id: 4,
    title: 'Advanced',
    bn_title: 'স্টক খাতা',
    image: '/images/features/advanced.svg',
    link: '#',
  },
];

export default SidebarLinks;
